#!/usr/bin/env bash
#  a Bash script that will display information about subdomains.
print_domain_info() {
	dig "$1" | grep -A1 'ANSWEER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}
if [ "$#" -eq 2 ]
then
	print_domain_info "$2.$1" "$2"
else
	print_domain_info "www.$1" "www"
	print_domain_info "1b-01.$1" "1b-01"
	print_domain_info "web-01.$1" "we-01"
	print_domain_info "web-02.$1" "web-02"
fi
