#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
FPATH=$1
IP=$2
UNAME=$3
KEY_PATH=$4
scp -i "$KEY_PATH" -o StrictHostKeyChecking=no "$FPATH" "$UNAME@$IP:~/"
