#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt update
sudo apt install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
sudo service nginx reload
