#!/usr/bin/env bash
# a bash script to make a backup for the database
mydate=$(date +"%d-%m-%Y")
sudo mysqldump --opt --all-databases -u root --password="$1" > backup.sql
sudo tar -czvf "$mydate.tar.gz" backup.sql
