#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs`
sudo sed -i '/listen \[::\]:80 default_server;/d' /etc/nginx/sites-available/default
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
