#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100
var=1
while [ $var -le 100 ]; do
	if (( var % 3 == 0 && var % 5 == 0 )); then
		echo "FizzBuzz"
	elif (( var % 3 == 0 )); then
		echo "Fizz"
	elif (( var % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$var"
	fi
	var=$((var+1))
done
