#!/usr/bin/env bash
#a Bash script that configures the container to fit the above requirements
sed -i 's/user[ \t]*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen[ \t]*80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
