#!/usr/bin/env bash
#a Bash script that configures the container to fit the above requirements
sudo adduser nginx
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo chown -R nginx:nginx /var/www/html
sudo service nginx restart
