#!/usr/bin/env bash
#a Bash script that configures the container to fit the above requirements
sudo sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo service nginx restart
