#!/usr/bin/env bash
# fix in 7 lines or less
udo sed -i 's/user .*/user nginx\n/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80\n/listen 8080\n/' /etc/nginx/sites-available/default
sudo systemctl restart nginx
