#!/usr/bin/env bash
# fix in 7 lines or less
udo sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo systemctl restart nginx
