#!/usr/bin/env bash
# a Bash script that configure connection to the server
{
  echo "Host *"
  echo "  IdentityFile ~/.ssh/school"
  echo "  PasswordAuthentication no"
} > /etc/ssh/ssh_config 
chmod 600 /etc/ssh/ssh_config
